name: Fetch Clouds Data

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run clouds data collection
        run: |
          bash data-workflow/scripts/fetch/cloudsdatacollection.sh

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data-workflow/raw/clouds
          git commit -m 'Update clouds data'
          git pull --rebase --autostash
          git push
        shell: bash
