name: Daily Data Workflow

on:
  schedule:
    - cron: "55 22 * * *"   # 23:58 Belgische tijd = 22:58 UTC
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest

    env:
      SOLAR_PASSWORD: ${{ secrets.SOLAR_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: pandoc texlive texlive-latex-extra texlive-fonts-recommended
          version: 1.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended

      - name: Cache pip packages
        uses: actions/cache@v4
        with: 
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('data-workflow/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r data-workflow/requirements.txt

      - name: Cache playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: |
            ${{ runner.os }}-playwright

      - name: Install chromium
        run: playwright install chromium

      - name: Fetch radiation data
        run: |
          bash data-workflow/scripts/fetch/radiationdatacollection.sh

      - name: Fetch solar data
        run: |
          python3 data-workflow/scripts/fetch/solardatacollection.py

      - name: Run data transform script
        run: |
          bash data-workflow/scripts/transform.sh
        continue-on-error: false

      - name: Run analysis script
        run: |
          python3 data-workflow/scripts/analyze.py

      - name: Generate report
        run: |
          bash data-workflow/scripts/generate_report.sh

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # git add data-workflow/raw/radiation
          # git add data-workflow/raw/solar
          # git add data-workflow/processed
          # git add data-workflow/analysis-output
          # git add data-workflow/report
          git add -A
          git commit -m 'Update radiation/solar + daily report update' || true

          git pull --rebase --autostash
          git push


